name: Deploy Website
'on':
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: executing remote ssh commands using password
        run: >
        
           sudo ssh -T -i "key.pem" ubuntu@ec2-3-91-60-196.compute-1.amazonaws.com

      - name: Install apache server
        run: >
           sudo apt update

           sudo apt install -y apache2

      - name: Copy HTML folder to remote server
        run: >
          cd /home/ubuntu &&
          git clone https://github.com/Akshay80/dummysite.git &&
          sudo cp -r /home/ubuntu/dummysite/* /var/www/html
      - name: Verify HTML folder on remote server
        run: >
           cd /var/www/html &&
           ls -a 

         
